Docs site
ayrat555/fang pull request #82
Opened 2022-09-05 22:41 UTC by pxp9

2022-09-06 19:39 UTC, ayrat555 approved these changes

2022-09-06 19:45 UTC, ayrat555 requested changes
buggy 🚗

2022-09-07 06:38 UTC, pxp9 commented on docs/deploy.sh
> +  printf "+++\ntitle = \"README\"\ndescription = \"Fang README\"\ndate = $TIME\nupdated = $TIME\ndraft = false\nweight = 410\nsort_by = \"weight\"\ntemplate = \"docs/page.html\"\n\n[extra]\nlead = \"
We have to delete description

2022-09-07 07:57 UTC, pxp9 commented on docs/deploy.sh
> +  printf "+++\ntitle = \"README\"\ndescription = \"Fang README\"\ndate = $TIME\nupdated = $TIME\ndraft = false\nweight = 410\nsort_by = \"weight\"\ntemplate = \"docs/page.html\"\n\n[extra]\nlead = \"
it think solve in [delete desc](https://github.com/ayrat555/fang/pull/82/commits/e3610e371047e58c899c7045843630aae2ea8740)

2022-09-07 16:22 UTC, ayrat555 approved these changes

2022-09-07 16:23 UTC, merged